(define (setup)
  #f)

(define (draw)
  (background 0 0 0)
  (fill 100 50 250 1)
  (text 20 (- *height* 40) "Please, enter this window with your mouse pointer.")
  (fill 255 0 0 1)
  (text *mouse-x* *mouse-y* "Hello world!")
  (fill 200 200 200 1)
  (text 0 0 (string-append "Mouse is at x:" (number->string *mouse-x*) " y:" (number->string *mouse-y*))))
